#!/usr/bin/env bash
#
# common.sh — shared configuration and helpers for the custom release build.
# Source this from every build script and from release.sh.
#
# shellcheck shell=bash

#=============================================================================
# Configuration — override any of these via environment
#=============================================================================

WORKSPACE="${WORKSPACE:-${HOME}/workspace}"
STATE_DIR="${STATE_DIR:-${WORKSPACE}/.release-state}"
IMAGES_JSON="${STATE_DIR}/images.json"

GITHUB_ORG="${GITHUB_ORG:-dmc5179}"
GIT_BRANCH="${GIT_BRANCH:-azure-il6-release-4.21}"

QUAY_NAMESPACE="${QUAY_NAMESPACE:-danclark}"
PUSH_REGISTRY="${PUSH_REGISTRY:-quay.io/${QUAY_NAMESPACE}}"

# Three auth contexts, generated by setup-auth.sh from the two credentials you
# supply. Each exists for a specific reason:
#
#   PULL_AUTH_FILE   the pull secret, unmodified. Reads Red Hat content:
#                    the base release and the ocp-v4.0-art-dev payload
#                    images, which are not anonymously readable. Used by
#                    oc-mirror.
#
#   BUILD_AUTH_DIR   the pull secret with its quay.io entry replaced by your
#                    token. A component build pulls base images from
#                    registry.ci.openshift.org and pushes to quay.io, both in
#                    one invocation — `make release-local` does both itself —
#                    so one credential set has to cover both. Overwriting
#                    quay.io is safe here because no build reads from quay.io.
#                    A directory because docker has no --authfile and only
#                    accepts `--config <dir>`; podman reads the config.json
#                    inside it.
#
#   RELEASE_AUTH_FILE  the pull secret plus your token filed under
#                    `quay.io:443`. Release assembly is the one step that must
#                    read from quay.io and push to quay.io at once, through a
#                    single --registry-config. Auth matching is a literal
#                    string compare, so `quay.io:443` is a second entry for the
#                    same host: reads match `quay.io` (pull secret), the push
#                    target is addressed as `quay.io:443` (your token).
#
PULL_AUTH_FILE="${PULL_AUTH_FILE:-${HOME}/.docker/config.json}"
BUILD_AUTH_DIR="${BUILD_AUTH_DIR:-${HOME}/.docker-build}"
BUILD_AUTH_FILE="${BUILD_AUTH_DIR}/config.json"
RELEASE_AUTH_FILE="${RELEASE_AUTH_FILE:-${HOME}/.docker/release-auth.json}"
RELEASE_PUSH_REGISTRY="${RELEASE_PUSH_REGISTRY:-quay.io:443/${QUAY_NAMESPACE}}"

BASE_RELEASE="${BASE_RELEASE:-quay.io/openshift-release-dev/ocp-release:4.21.1-x86_64}"
OC="${OC:-oc-4.21.5}"

#=============================================================================
# Output helpers
#=============================================================================

if [[ -t 1 ]]; then
    C_RESET=$'\033[0m'; C_BLUE=$'\033[1;34m'; C_GREEN=$'\033[1;32m'
    C_YELLOW=$'\033[1;33m'; C_RED=$'\033[1;31m'
else
    C_RESET=""; C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_RED=""
fi

log()  { printf '%s==>%s %s\n' "${C_BLUE}"   "${C_RESET}" "$*"; }
ok()   { printf '%s  ok%s %s\n' "${C_GREEN}"  "${C_RESET}" "$*"; }
warn() { printf '%swarn%s %s\n' "${C_YELLOW}" "${C_RESET}" "$*" >&2; }
err()  { printf '%s err%s %s\n' "${C_RED}"    "${C_RESET}" "$*" >&2; }
die()  { err "$*"; exit 1; }

#=============================================================================
# Repo management
#=============================================================================

# clone_or_update <repo-name>
# Leaves the repo at ${WORKSPACE}/<repo-name> on ${GIT_BRANCH}.
clone_or_update() {
    local repo="$1" dir="${WORKSPACE}/$1"

    if [[ -d "${dir}/.git" ]]; then
        ok "${repo} already cloned at ${dir}"
        return 0
    fi

    log "Cloning ${repo} (branch ${GIT_BRANCH})"
    git clone -b "${GIT_BRANCH}" "https://github.com/${GITHUB_ORG}/${repo}.git" "${dir}"
    ok "Cloned ${repo}"
}

# short_sha <repo-dir> — the tag most of these Makefiles derive from HEAD.
#
# Only safe as a fallback. `git rev-parse --short` picks the shortest
# unambiguous length for the repo, which can exceed the fixed 7 characters a
# Makefile truncates to — cloud-provider-azure returns 9 here but tags with 7.
short_sha() {
    git -C "$1" rev-parse --short HEAD
}

# discovered_tag <runtime> <repo> — read the tag off the image the build just
# produced, rather than recomputing what the Makefile chose.
discovered_tag() {
    local runtime="$1" repo="$2"
    "${runtime}" images --format '{{.Tag}}' "${repo}" 2>/dev/null \
        | grep -vx '<none>' | head -1
}

#=============================================================================
# Image digests
#=============================================================================

# remote_digest <image-ref>
#
# Always resolve digests from the registry, never from `podman inspect`. The
# local manifest digest can differ from what the registry stores, and feeding a
# local digest to `oc adm release new` produces "manifest unknown".
# Reads the pushed image back, so it authenticates with the push credential.
# The quay repos are public, but using the push file keeps this working if they
# are ever made private.
remote_digest() {
    local ref="$1" digest
    digest=$(skopeo inspect --authfile "${BUILD_AUTH_FILE}" "docker://${ref}" 2>/dev/null | jq -r '.Digest // empty')
    [[ -n "${digest}" ]] || return 1
    echo "${digest}"
}

#=============================================================================
# Build state
#
# Each build script records the image it produced; release.sh consumes these.
# Keys are the OpenShift release component names that `oc adm release new`
# expects, not the repo names.
#=============================================================================

init_state() {
    mkdir -p "${STATE_DIR}"
    [[ -f "${IMAGES_JSON}" ]] || echo '{}' > "${IMAGES_JSON}"
}

# replace_file <src> <dest> — atomic overwrite.
#
# `command mv -f` rather than plain `mv`: interactive shells commonly alias mv
# to `mv -i` (prompts, hangs a script) or `mv -n` (silently refuses to
# overwrite, so the update is lost with a zero exit code).
replace_file() {
    command mv -f "$1" "$2"
}

# record_image <release-component-name> <image-ref-with-digest>
record_image() {
    local component="$1" ref="$2"
    init_state
    local tmp="${IMAGES_JSON}.tmp"
    jq --arg k "${component}" --arg v "${ref}" '.[$k] = $v' "${IMAGES_JSON}" > "${tmp}"
    replace_file "${tmp}" "${IMAGES_JSON}"
    ok "Recorded ${component} = ${ref}"
}

# get_image <release-component-name>
get_image() {
    [[ -f "${IMAGES_JSON}" ]] || return 1
    local v
    v=$(jq -r --arg k "$1" '.[$k] // empty' "${IMAGES_JSON}")
    [[ -n "${v}" ]] || return 1
    echo "${v}"
}

# record_and_report <release-component-name> <image-ref-without-digest>
# Resolves the remote digest and records <repo>@<digest>.
record_and_report() {
    local component="$1" ref="$2"
    local digest repo="${ref%:*}"

    log "Resolving remote digest for ${ref}"
    if ! digest=$(remote_digest "${ref}"); then
        die "Could not read digest for ${ref}. Is it pushed, and is ${BUILD_AUTH_FILE} valid?"
    fi
    record_image "${component}" "${repo}@${digest}"
}

#=============================================================================
# Preflight shared by build scripts
#=============================================================================

require_cmd() {
    local c
    for c in "$@"; do
        command -v "${c}" >/dev/null 2>&1 || die "${c} is not installed. Run prereq.sh first."
    done
}

# has_registry <auth-file> <registry>
has_registry() {
    jq -e --arg r "$2" '.auths | has($r)' "$1" >/dev/null 2>&1
}

# require_auth_file <file> <registry>...
#
# Checks the registries are actually present, not just that the file exists.
# Without this a build clones the repo and runs for a while before failing on
# an opaque "authentication required" from the base-image pull.
require_auth_file() {
    local file="$1"; shift
    [[ -f "${file}" ]] || die "${file} not found. Run ./setup-auth.sh first."

    local reg missing=()
    for reg in "$@"; do
        has_registry "${file}" "${reg}" || missing+=("${reg}")
    done
    (( ${#missing[@]} )) || return 0

    err "${file} has no credentials for: ${missing[*]}"
    for reg in "${missing[@]}"; do
        if [[ "${reg}" == registry.ci.openshift.org ]]; then
            err "  ${reg} — base images for every container build."
            err "    Token: https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com"
        fi
    done
    err "Run ./setup-auth.sh to rebuild the auth files."
    exit 1
}

# Every component build pulls base images from the CI registry and pushes to
# quay.io using this one context.
require_build_auth() {
    require_auth_file "${BUILD_AUTH_FILE}" registry.ci.openshift.org quay.io
}

require_pull_auth() {
    require_auth_file "${PULL_AUTH_FILE}" "$@"
}

# require_release_auth — the merged file used only for release assembly.
require_release_auth() {
    [[ -f "${RELEASE_AUTH_FILE}" ]] \
        || die "Release auth ${RELEASE_AUTH_FILE} not found. Run ./setup-auth.sh first."
    has_registry "${RELEASE_AUTH_FILE}" "quay.io" \
        || die "${RELEASE_AUTH_FILE} has no quay.io entry (needed to read the release payload)."
    has_registry "${RELEASE_AUTH_FILE}" "quay.io:443" \
        || die "${RELEASE_AUTH_FILE} has no quay.io:443 entry (needed to push the release)."
}

mkdir -p "${WORKSPACE}"
